//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8POC.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public long FramesPerSecond {
            get {
                return ((long)(this["FramesPerSecond"]));
            }
            set {
                this["FramesPerSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public long CyclesPerFrame {
            get {
                return ((long)(this["CyclesPerFrame"]));
            }
            set {
                this["CyclesPerFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C8POC.Plugins.Graphics.SDLPlugin.SDLPlugin")]
        public string SelectedGraphicsPlugin {
            get {
                return ((string)(this["SelectedGraphicsPlugin"]));
            }
            set {
                this["SelectedGraphicsPlugin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C8POC.Plugins.Sound.ConsoleBeep.ConsoleSoundBeepPlugin")]
        public string SelectedSoundPlugin {
            get {
                return ((string)(this["SelectedSoundPlugin"]));
            }
            set {
                this["SelectedSoundPlugin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C8POC.Plugins.Keyboard.SystemWindowsKeyboard.SystemWindowsKeyboardPlugin")]
        public string SelectedKeyboardPlugin {
            get {
                return ((string)(this["SelectedKeyboardPlugin"]));
            }
            set {
                this["SelectedKeyboardPlugin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisassemblerEnabled {
            get {
                return ((bool)(this["DisassemblerEnabled"]));
            }
            set {
                this["DisassemblerEnabled"] = value;
            }
        }
    }
}
